#!/bin/bash

# Possible slot management implmentatoin.
# This can be called by a systemd service and will increment
# the "slot" launced each time. If a slot file i not present it goes to the next one.
# To start the next slot call tpu_slotman start

bin_name="slot_entry"
home_dir="/home/mendel/"

next_slot_file(){
    sl=$(cat next_slot || echo "0")
    printf "slot%d/" $sl
    sl=$(( $sl + 1 ))
    sl=$(( $sl % 4 ))
    echo $sl > next_slot
}

start(){
    echo pwd:$(pwd)
    for slot in "slot0" "slot1" "slot2" "slot3"
    do
	    cd $home_dir$slot
	    sudo ./boot_increment
    done
    cd $home_dir
    dir=$(next_slot_file)
    echo $home_dir$dir$bin_name
    while [ ! -f $home_dir$dir$bin_name ]; do
        file=$(next_slot_file)
    done
    cd $home_dir$dir
    $home_dir$dir$bin_name
}

${@}
