#!/bin/bash

# Possible slot management implmentatoin.
# This can be called by a systemd service and will increment
# the "slot" launced each time. If a slot file i not present it goes to the next one.
# To start the next slot call tpu_slotman start

bin_name="tpu_csp"
bin_dir="/home/foo/bar"

next_slot_file(){
    sl=$(cat next_slot || echo "0")
    printf "%s-%d" $bin_name $sl
    sl=$(( $sl + 1 ))
    sl=$(( $sl % 4 ))
    echo $sl > next_slot

}

start(){
    file=$(next_slot_file)
    while [ ! -f $bin_dir$file ]; do
        file=$(next_slot_file)
    done
    $bin_dir$file &
}

${@}
